# Generated by Django 5.1.5 on 2025-03-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование категории",
                        max_length=100,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите краткое описание категории",
                        null=True,
                        verbose_name="описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name", "description"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование продукта",
                        max_length=100,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите краткое описание продукта",
                        null=True,
                        verbose_name="описание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Загрузите изображение продукта",
                        upload_to="catalog/product_images",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        blank=True,
                        help_text="Введите цену за покупку",
                        null=True,
                        verbose_name="цена за покупку",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Введите дату создания заказа",
                        max_length=20,
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату последнего изменения заказа",
                        max_length=20,
                        null=True,
                        verbose_name="дата последнего изменения",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подукт",
                "verbose_name_plural": "Продукты",
                "ordering": [
                    "description",
                    "category",
                    "price",
                    "created_at",
                    "updated_at",
                ],
            },
        ),
    ]
