# Generated by Django 5.1.5 on 2025-04-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_image_alter_product_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "description",
                    "category",
                    "price",
                    "created_at",
                    "updated_at",
                ],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Подукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Опубликован"),
        ),
    ]
